server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # même rôle que le proxy de vite en dev
    location /api {
        proxy_pass http://backend:3000;
    }

    # React Router : toutes les routes renvoient index.html
    location / {
        try_files $uri /index.html;
    }
}
